# Generated by Django 3.1.2 on 2020-11-03 16:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_spending_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='total_payed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='spending',
            name='total_to_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
