# Generated by Django 3.1.2 on 2020-11-03 17:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201103_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='total_payed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='spending',
            name='total_to_pay',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
