# Generated by Django 3.1.2 on 2020-11-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201103_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Spendings', to='core.Tag'),
        ),
    ]
