# Generated by Django 3.2.3 on 2021-06-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210603_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='linked_transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transaction'),
        ),
    ]
