# Generated by Django 3.2.3 on 2021-06-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction_linked_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('TO', 'Transfer Input'), ('TO', 'Transfer Output'), ('I', 'Income'), ('E', 'Expense')], max_length=2),
        ),
    ]
