# Generated by Django 3.1.2 on 2020-11-04 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201104_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spending',
            old_name='total_to_pay',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='total_payed',
        ),
        migrations.CreateModel(
            name='TermTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_spending', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='terms', through='core.TermTag', to='core.Tag'),
        ),
    ]
