# Generated by Django 3.1.2 on 2020-11-04 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201104_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='tags',
        ),
        migrations.AlterField(
            model_name='termtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='termtag',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.term'),
        ),
    ]
