# Generated by Django 3.1.2 on 2020-11-04 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201104_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
