# Generated by Django 3.2.5 on 2021-07-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('C', 'Checking Account'), ('S', 'Savings'), ('I', 'Investments'), ('W', 'Wallet')], default='C', max_length=1),
        ),
    ]
