# Generated by Django 3.1.2 on 2020-11-04 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_spending_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
