# Generated by Django 3.2.12 on 2022-03-20 07:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_budget_budgetcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2022, max_length=4)),
                ('month', models.PositiveSmallIntegerField(default=3, max_length=2)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.account')),
            ],
        ),
    ]
